apiVersion: batch/v1
kind: Job
metadata:
  name: mybackup-job
spec:
  backoffLimit: 4
  template:
    metadata:
      name:
        mybackup-image
    spec:
      containers:
        - name: mybackup-container
          image: busybox
          ports:
            - containerPort: 80
      restartPolicy: Never

